### ISSUE TITLE
发现一个小bug

### ISSUE THREAD

**Issue by ouyangwenfeng** [ta893115871/StickyNavLayout#5]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void in.srain.cube.views.ptr.PtrClassicFrameLayout.refreshComplete()' on a null object reference
                                                                         at com.gxz.stickynavlayout.activity.TopViewOverOneScreenActivity$Work.onPostExecute(TopViewOverOneScreenActivity.java:118)
                                                                         at com.gxz.stickynavlayout.activity.TopViewOverOneScreenActivity$Work.onPostExecute(TopViewOverOneScreenActivity.java:107)
                                                                         at android.os.AsyncTask.finish(AsyncTask.java:636)
                                                                         at android.os.AsyncTask.access$500(AsyncTask.java:177)
                                                                         at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:135)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5669)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by ta893115871** [comment]
这个是AsyncTask 问题， 为了测试，没有处理销毁activity的时候取消AsyncTask。
