### ISSUE TITLE
嵌套SmartRefreshLayout后出现mViewPager  should be  used  FragmentPagerAdapter or  FragmentStatePagerAdapter  !

### ISSUE THREAD

**Issue by tom0gao** [ta893115871/StickyNavLayout#51]
嵌套SmartRefreshLayout后出现mViewPager  should be  used  FragmentPagerAdapter or  FragmentStatePagerAdapter  !

**Comment by yanchengdeng** [comment]
the same issues

 java.lang.RuntimeException: mViewPager  should be  used  FragmentPagerAdapter or  FragmentStatePagerAdapter  !
                                                                       at com.gxz.library.StickyNavLayout.getCurrentScrollView(StickyNavLayout.java:406)
                                                                       at com.gxz.library.StickyNavLayout.dispatchTouchEvent(StickyNavLayout.java:219)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                                       at in.srain.cube.views.ptr.PtrFrameLayout.dispatchTouchEventSupper(PtrFrameLayout.java:265)
                                                                       at in.srain.cube.views.ptr.PtrFrameLayout.dispatchTouchEvent(PtrFrameLayout.java:339)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                                       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:607)
                                                                       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1890)
                                                                       at android.app.Activity.dispatchTouchEvent(Activity.java:3240)
                                                                       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
                                                                       at com.android.tools.profiler.support.event.WindowProfilerCallback.dispatchTouchEvent(WindowProfilerCallback.java:69)
                                                                       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:569)
                                                                       at android.view.View.dispatchPointerEvent(View.java:11008)
                                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5162)
                                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5014)
                                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4539)
                                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4592)
                                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4558)
                                                                       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4691)
                                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4566)
                                                                       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4748)
                                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4539)
                                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4592)
                                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4558)
                                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4566)
                                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4539)
                                                                       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7098)
                                                                       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7030)
                                                                       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6991)
                                                                       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7208)
                                                                       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
                                                                       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7172)
                                                                       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7235)
04-26 01:04:10.471 22691-22691/net.zgxyzx.mobile E/AndroidRuntime:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:959)
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:734)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:664)
                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:945)
                                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
